trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Infrastructure

stages:
- stage: 'Build_Stage' #Stage name cannot have spaces
  displayName: 'Validate ARM' #Name displayed when viewing in Azure DevOps
  jobs:
  - job: 'Build_Job' #Job name cannot have spaces
    displayName: 'ARM Validation' #Name displayed when viewing in Azure DevOps
    variables:
    - group: Auth0ToApplicationInsight
    pool:
      vmImage: 'windows-2022'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(subscription)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroup)
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/Deploy.json'
        deploymentMode: 'Validation'
        deploymentName: 'Auth0ToApplicationInsight'
        # auth0LogConnectionString: $auth0LogConnectionString
        # company: $(company)
        # eventGridTopicName: $(eventGridTopicName)
        # eventGridSubscriptionName: $(eventGridSubscriptionName)
        overrideParameters: >-
          -company $(company) -eventGridTopicName $(eventGridTopicName) -eventGridSubscriptionName $(eventGridSubscriptionName) 
          -functionName $(functionName)  -auth0LogConnectionString $(auth0LogConnectionString) -subscription $(subscription)
          -subscriptionId $(subscriptionId)
- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
#- ${{ if true }}:
  - stage: 'Stage' #Stage name cannot have spaces
    dependsOn:
      - Build_Stage
    displayName: 'Infrastructure' #Name displayed when viewing in Azure DevOps
    variables:
    - group: Auth0ToApplicationInsight
    jobs:
    - deployment: 'Deploy' #Job name cannot have spaces
      displayName: 'Infrastructure' #Name displayed when viewing in Azure DevOps
      variables:
        resourceGroup: '$(resourceGroup)' 
        subscription: '$(subscription)'
        deploymentName: 'Auth0ToApplicationInsight'
      pool:
        vmImage: 'windows-2022'
      environment: Auth0ToApplicationInsight
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: '$(subscription)'
                subscriptionId: '$(subscriptionId)'
                action: 'Create Or Update Resource Group'
                resourceGroupName: $(resourceGroup)
                location: '$(location)'
                templateLocation: 'Linked artifact'
                csmFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/Deploy.json'
                deploymentMode: 'Incremental'
                deploymentName: '$(deploymentName)'
                # auth0LogConnectionString: $auth0LogConnectionString
                # company: $(company)
                # eventGridTopicName: $(eventGridTopicName)
                # eventGridSubscriptionName: $(eventGridSubscriptionName)
                overrideParameters: >-
                  -company $(company) -eventGridTopicName $(eventGridTopicName) -eventGridSubscriptionName $(eventGridSubscriptionName) 
                  -functionName $(functionName)  -auth0LogConnectionString $(auth0LogConnectionString) -subscription $(subscription)
                  -subscriptionId $(subscriptionId)

