trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - Infrastructure

stages:
- stage: 'Build_Stage' #Stage name cannot have spaces
  displayName: 'Validate ARM' #Name displayed when viewing in Azure DevOps
  jobs:
  - job: 'Build_Job' #Job name cannot have spaces
    displayName: 'ARM Validation' #Name displayed when viewing in Azure DevOps
    variables:
    - group: Auth0ToApplicationInsight
    pool:
      vmImage: 'windows-2022'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(azureResurceManagerConnection)'
        subscriptionId: '$(subscriptionId)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroup)
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/Deploy.json'
        deploymentMode: 'Validation'
        deploymentName: 'Auth0ToApplicationInsight'
        overrideParameters: >-
          -uniquePrefixName $(uniquePrefixName) -auth0LogConnectionString $(auth0LogConnectionString) -sharedLawId $(sharedLawId)

#- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
- stage: 'ProdEnv_Stage' #Stage name cannot have spaces
  dependsOn:
    - Build_Stage
  displayName: 'InfrastructureDeploy' #Name displayed when viewing in Azure DevOps
  #condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  variables:
  - group: Auth0ToApplicationInsight
  jobs:
  - deployment: 'Deploy' #Job name cannot have spaces
    displayName: 'Infrastructure' #Name displayed when viewing in Azure DevOps
    pool:
      vmImage: 'windows-2022'
    environment: Auth0ToApplicationInsight
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureResurceManagerConnection)'
              subscriptionId: $(subscriptionId)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(resourceGroup)
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/Infrastructure/ARM/Deploy.json'
              deploymentMode: 'Incremental'
              deploymentName: 'Auth0ToApplicationInsight'
              overrideParameters:  >-
                -uniquePrefixName $(uniquePrefixName) -auth0LogConnectionString $(auth0LogConnectionString) -sharedLawId $(sharedLawId)
